### PR TITLE
Nsxv plugin Enhancements

### PR DESCRIPTION
**Pull request by rarcotvmw**
The header options for the nsx policy will support securitygroup securitygroup-id as the target options. These are optional. If these target options are given, all the rules in the section will have appliedTo as the given Security Group.
If the values are not given, the appliedTo will be default to DISTRIBUTED_FIREWALL

### CODE REVIEW

**Comment by ankenyr** [comment]
Hi @rarcotvmw,
You will need to address the problems the googlebot pointed out about the CLA.

**Comment by rarcotvmw** [comment]
VMware

**Comment by rarcotvmw** [comment]
I signed it!

**Comment by ankenyr** [comment]
Hi @rarcotvmw, sorry this sat for so long. My team had a summit and then I was on vacation shortly afterwards. Can you please resolve the conflicts and once it is done let me know so I can take a look.

**Comment by ankenyr** [comment]
I am not sure why you have the PR setup like this. There are many commits which are already present. The only commit you should be trying to push is 67e12fc6cacc028ae5fa0b040d7d1566046d305a as all of the other commits have been merged. Many of those commits are already commited. If there is something within those commits that is needed then that needs to be separated out.

**Comment by rarcotvmw** [comment]
When I initially submitted a pull request, I could just see my changes 67e12fc. Not sure now, I see other commits too. Please let me know how I can have only change 67e12fc in the pull request.

**Comment by rarcotvmw** [comment]
Nsxv plugin Enhancments - 67e12fc
Minor changes for Google Capirca Enhancements for applied to. - 4e9dd24

**Comment by rarcotvmw** [comment]
Hi Rob, closing this pull request. Opened a new one and that has only 1 commit (changes made for nsxv plugin enhancments).

Thank you

**Pull request closed without merging**
