### PR TITLE
Adding content to README

### PR DESCRIPTION
**Pull request by eimann**
This will add the supported platforms to README.md and also corrects a typo.
Instructions on how to use and requirements will follow soon.

### CODE REVIEW

**Comment by jzohrab** [comment]
Hello @vklimovs, I'm not the submitter of this PR.  Are you interested in this, though?  I've just started trying Caprica and have a few other small suggestions for the README.  I could also rebase this one so it can get pulled in.

I know you're aiming for a release soon of some internal changes, per https://github.com/google/capirca/pull/48, and won't submit a PR if you're going to make many changes.  Regards, Jeff

**Comment by vklimovs** [comment]
This one is small enough - please rebase.

**Comment by jzohrab** [comment]
Actually, I'm going to leave this one to @eimann - it looks like this is two separate things: README fixes, and adding Juniper.  This PR specifically says README changes only, so maybe there are some unintended commits in there.

**Comment by eimann** [comment]
I haven't hat time yet to brush it up any further. So I'm just going to close this PR for now.

**Pull request closed without merging**
