### PR TITLE
Fix header comment generation

### PR DESCRIPTION
**Pull request by zombah**
With strict condition for platfrom
cisco and filter type standard

Signed-off-by: Misha Komarovskiy <zombah@gmail.com>

### CODE REVIEW

**Comment by ankenyr** [comment]
Can you create tests for these?

**Comment by zombah** [comment]
@ankenyr You mean to expand testRemark with header remark check? 
I think i can try, but cisco_test.py already failing for me at current master with FAIL: testExpiringTerm (tests.lib.cisco_test.CiscoTest)  is it know problem?

**Comment by ankenyr** [comment]
I am looking for tests to be made for cisco to confirm it has the expected results and that its child variants have their expected results.
As for tests failing that is unexpected, I don't see travis reporting it is failing. Got any more details you can share on what exactly is happening?

**Comment by zombah** [comment]
That was temporary fail, after couple runs it vanished, i didn't figured why.
I expanded cisco testRemark for standard filter type.

**Comment by zombah** [comment]
I don't have access to arista platform so i'm not sure of proper remarking style there, but i can forge remark test based on their documentation.

**Comment by zombah** [comment]
@ankenyr @Manningham I added tests, please review

**Comment by zombah** [comment]
@ankenyr it seems my pr need rebase now, do i need to care about this or there is no chances to receive any reviewson this patch?

**Comment by ankenyr** [comment]
So sorry I let this linger for so long. I changed things to resolve the conflict and fix it for the latest addition of verbosity settings. This should look good, just letting travis do its thing and will accept it after.

**Pull request merged**
