### PR TITLE
Cisco NXOS Support

### PR DESCRIPTION
**Pull request by sjtarik**
This will add Cisco NXOS ACL Support and the object-groups support for NXOS.

### CODE REVIEW

**Comment by fischa** [comment]
Hi,
is there a chance this PR is merged in the next time. I'm not a developer but the failing test seems unrelated (Juniper SRX test) to me.

**Comment by ankenyr** [comment]
Hi @fischa the current PR is large and I requested it to be broken into smaller chunks for review. This has not happened yet. If you would like to take a stab at making smaller PR's and submit them I would be happy to review them.

**Comment by fischa** [comment]
Hi @ankenyr, thanks for the update. I'll check with a developer if we can do something about it.

**Comment by ankenyr** [comment]
Cool, before submitting a PR please make sure to break it down into smaller chunks that fix individual tasks. I am going to mark this PR as closed but will be happy to take a look at smaller ones.

**Pull request closed without merging**
