### PR TITLE
Security Fix for Insecure Deserialization - huntr.dev

### PR DESCRIPTION
**Pull request by huntr-helper**
https://huntr.dev/users/B3EF has fixed the Insecure Deserialization vulnerability 🔨. Think you could fix a vulnerability like this?

Get involved at https://huntr.dev/

Q | A
Version Affected | ALL
Bug Fix | YES
Original Pull Request | https://github.com/418sec/capirca/pull/1
Vulnerability README | https://github.com/418sec/huntr/blob/master/bounties/pip/caprica/1/README.md

### 📊 Metadata *

Arbitrary code execution fix

### ⚙️ Description *

Capirca is a tool designed to utilize common definitions of networks, services and high-level policy files to facilitate the development and manipulation of network access control lists (ACLs) for various platforms. It was developed by Google for internal use, and is now open source.
This package is vulnerable to Arbitrary code execution via Insecure YAML deserialization due to the use of a known vulnerable function load() in yaml. <br> repo: https://github.com/google/capirca

### 💻 Technical Description *

This package was vulnerable to Arbitrary code execution due to the use of a known vulnerable load() with a vulnerable loader function in YAML. Changing that to SafeLoader will fix the issue.

### 👍 User Acceptance Testing (UAT)

I have just changed the load function to safe_load it ain't going to break anything

### CODE REVIEW

**Comment by JamieSlome** [comment]
@googlebot I signed it!

**Comment by JamieSlome** [comment]
@B3EF - are you able to sign the CLA? Let me know if you have any trouble! 🍰

**Comment by B3EF** [comment]
@googlebot I signed it

**Comment by B3EF** [comment]
@googlebot I signed it!

**Comment by JamieSlome** [comment]
@googlebot I signed it!

**Comment by nero85** [comment]
This was fixed with the commit df7711fd23f7f8715865067955eadf9d883bd0e7, closing this PR. Thanks!

**Pull request closed without merging**
