### PR TITLE
add missing pips to requirements.txt

### PR DESCRIPTION
**Pull request by egon010**

### CODE REVIEW

**Comment by ankenyr** [comment]
It looks like you are missing mox, can you please make sure to add that?

**Comment by egon010** [comment]
I signed it!

**Comment by ankenyr** [comment]
Hi @egon010,
The bots seem to think you are still missing the CLA. Mox was removed in https://github.com/google/capirca/commit/771ce63b0e669674e90df792d17756c59b8f4da7 and https://github.com/google/capirca/commit/ef1a05917f8445d82c77002cc416227e4d992d84 so I believe this is ready to submit.

**Comment by jzohrab** [comment]
I've added these reqs in PR #71 as well.

**Comment by jzohrab** [comment]
This PR can be closed, as #71 incorporates these changes.

**Pull request closed without merging**
