### PR TITLE
Changed logging.basicConfig calls to logging.set_verbosity to work with absl logging

### PR DESCRIPTION
**Pull request by amybabay**
Trying to run aclgen with --debug or --verbose would fail with "AttributeError: 'module' object has no attribute 'basicConfig'"

Changing logging.basicConfig calls to use absl's logging.set_verbosity instead fixed the issue

### CODE REVIEW

**Comment by ankenyr** [comment]
Hi @amybabay,
Would you be able to sign the SLA?

**Comment by amybabay** [comment]
Hi @ankenyr ! Sorry for the delay -- I know it's a super small fix, but I'm sorting out whether I actually need my company to sign or not...

**Comment by ankenyr** [comment]
No worries, I am in no rush.

**Comment by ankenyr** [comment]
It looks like you are trying to combine the fix for #166 into this PR, can you please separate them into different PRs? You will still need to sign the CLA before I can take a look at the code itself. We cannot accept code changes without the CLA being signed.

**Comment by amybabay** [comment]
Sorry about that...definitely did that in the wrong branch. I'll close this and make a new clean request -- CLA stuff should be resolved next week.

**Pull request closed without merging**
