### PR TITLE
moved the return statement for the next_verbatim for loops up one level

### PR DESCRIPTION
**Pull request by kaibabbob**
They were indented at the wrong level
I am reopening PR #183, which was closed without the code fixes actually being applied.

### CODE REVIEW

**Comment by kaibabbob** [comment]
I have already signed the CLA.  None of the suggestions is working to resolve the issue so I am assuming that google-cla is hosed up.  In any case I am not able to proceed any further with this.

**Comment by rdsharma** [comment]
I don't think you actually replied to Googlebot to get it to verify, try that? I'm not allowed to review this without CLA.

**Comment by ankenyr** [comment]
Hi David,
I tried looking up your github username and the email you used, which looks like a no-reply fake email, and I cannot see your CLA. If you signed the CLA and used your real email then your github commits need to be associated with that. The instructions specify that here

> Individual signers
> It's possible we don't have your GitHub username or you're using a different email address on your commit. Check your existing CLA data and verify that your email is set on your git commits.

After you have fixed either the commit or your CLA you will want to follow what Rajeev and Googlebot said and reply to Googlebot saying you signed the CLA to re-trigger the check.

**Comment by kaibabbob** [comment]
I have changed my email settings so that my email is not private any longer, in case that is the issue.  But I still get the same message from the CLA site.  I appreciate your help.

`It looks like you've already signed this CLA. If you'd like to edit your contact information, you may do so below.

* required fields

Date Signed
Mar 13, 2020 10:37 PDT
Email(s)
Learn more about managing email addresses for your account.

David.Russell@dowjones.com
David.Russell@dowjones.com.test-google-a.com
david.russell.dowjones.com@g.dowjones.com
Name *
David Russell
`

**Comment by ankenyr** [comment]
Couple things
1) You are commiting from a company email, you may wish to consult with your legal team about if you are able to commit this.
2) Your CLA lists your work email but it doesn't associate it with your Github account. There is no way for CLA bot to tie things together considering your commits were made with the anonymous email. You can either update your CLA with your Github account (easy) or fix your commits to use the work email (hard). Once you are done with either of those you will want to invoke googlebot as instructed above.

**Comment by kaibabbob** [comment]
>update your CLA with your Github account (easy) 

maybe easy for you :)   but I am going around in circles trying to find any links for updating the CLA with my Github account.

**Comment by ankenyr** [comment]
Visit https://cla.developers.google.com/clas
click "Edit Contact Information"
You should see a section listing the date you signed it, your emails, and github account. I have included a screenshot with information redacted to show an example.
CLA

When you click on "Edit Contact Information" does it show the Github account entry? Is it blank? Is it filled in?

**Comment by kaibabbob** [comment]
Got it.  That was easy after seeing the bright red line in your posting.

There was no username listed and the data entry box outline was so feint as to be nearly invisible.

**Comment by kaibabbob** [comment]
It still seems to be failing despite entering my username on the form.

David Russell
CCIE #5751
NETWORK ARCHITECT
[image: NewsTech] <http://www.newscorp.com/>
M: +1 610 909 1129 <+1+555+555+5555>    O: +1 609 520 4458 <+1+555+555+5555>
E: david.russell@dowjones.com <Charles.Bergstresser@dowjones.com>
A: PO Box 300, Princeton, NJ 08543-0300

**Comment by kaibabbob** [comment]
I have signed the CLA

**Comment by ankenyr** [comment]
David, the instructions say

> Once you've signed (or fixed any issues), please reply here with `@googlebot I signed it!` and we'll verify it.

You must include the `@googlebot` part. This invoked the robot account googlebot similar to if I was to write @kaibabbob on another PR, it notified you of my mentioning of your username on that PR.

**Comment by ankenyr** [comment]
I guess anyone can invoke the googlebot on your behalf haha

**Comment by kaibabbob** [comment]
I have learned my lesson now.  Thanks for helping a newbie.

**Comment by sjtarik** [comment]
@kaibabbob any progress on this? seems to be breaking arista as well since it is derived from Cisco Policy generator as well.

**Comment by kaibabbob** [comment]
The screen says that I am not authorized to merge the pull request so I have been hoping that someone who is authorized would do it or let me know what I can do.  Its been a year and a half.

**Comment by sjtarik** [comment]
@rdsharma is capirca officially dead?

**Comment by rdsharma** [comment]
No, it's certainly not dead, just look at the revision log. Plenty of commits went in over the last few months.

Sorry for the delay on this one, I started bringing this into our internal repo then realized I needed to work with another team to verify impact on existing ACLs before merging it, and forgot to kick that process now. Will message some people about that now.

**Comment by rdsharma** [comment]
@kaibabbob would you mind rebasing this CL? Getting some merge conflicts now. Or if easier, I can just make an identical commit for you on top of HEAD then merge that, and give you attribution in the commit message.

**Comment by kaibabbob** [comment]
The latter please :)

David

David Russell
NETWORK ARCHITECT
[image: NewsTech] <http://www.newscorp.com/>
M: +1 610 909 1129    O: +1 609 520 4458
E: ***@***.***
A: PO Box 300, Princeton, NJ 08543-0300

**Pull request closed without merging**
